#!/usr/bin/env Rscript
options(warn=-1)
options("width"=200)
options(error=function(){traceback(3); quit(save="no", status=1, runLast=FALSE)})

suppressMessages(library(dplyr))
suppressMessages(library(Seurat))
suppressMessages(library(stringr))
suppressMessages(library(modules))
suppressMessages(library(argparse))

HERE <- (function() {return (dirname(sub("--file=", "", commandArgs(trailingOnly=FALSE)[grep("--file=", commandArgs(trailingOnly=FALSE))])))})()
suppressMessages(debug <- modules::use(file.path(HERE, "modules/debug.R")))
suppressMessages(io <- modules::use(file.path(HERE, "modules/io.R")))
suppressMessages(prod <- modules::use(file.path(HERE, "modules/prod.R")))


## ----
get_args <- function(){
    parser <- ArgumentParser(description="Single-cell RNA-Seq BD Rhapsody Import")
    parser$add_argument(
        "--rds",
        help=paste(
            "Path to the RDS file(s) to load Seurat object(s) from. These files",
            "should be generated by the BD Rhapsody Sequence Analysis Pipeline",
            "and include Sample_Tag metadata column."
        ),
        type="character", required="True", nargs="+"
    )
    parser$add_argument(
        "--metadata",
        help=paste(
            "Path to the TSV/CSV file to assign names to the sample tags. This",
            "file must include exactly two columns. First column is a 'sample_tag'.",
            "It should correspond to all unique values from the 'Sample_Tag' column",
            "of the loaded Seurat object(s). Second column may have an arbitrary name.",
            "But it should include unique names for each sample tag."
        ),
        type="character", required="True"
    )
    parser$add_argument(
        "--split",
        help=paste(
            "When assigning names to the sample tags, split each of",
            "them by origin (the RDS file the data was loaded from).",
            "Default: do not split"
        ),
        action="store_true"
    )
    parser$add_argument(
        "--verbose",
        help="Print debug information. Default: false",
        action="store_true"
    )
    parser$add_argument(
        "--h5ad",
        help=paste(
            "Save raw counts from the RNA assay to h5ad file.",
            "Default: false"
        ),
        action="store_true"
    )
    parser$add_argument(
        "--output",
        help="Output prefix. Default: ./sc",
        type="character", default="./sc"
    )
    parser$add_argument(
        "--cpus",
        help="Number of cores/cpus to use. Default: 1",
        type="integer", default=1
    )
    parser$add_argument(
        "--memory",
        help=paste(
            "Maximum memory in GB allowed to be shared between the workers",
            "when using multiple --cpus.",
            "Default: 32"
        ),
        type="integer", default=32
    )
    parser$add_argument(
        "--seed",
        help="Seed number for random values. Default: 42",
        type="integer", default=42
    )
    args <- parser$parse_args(str_subset(commandArgs(trailingOnly=TRUE), "\\.R$", negate=TRUE))  # to exclude itself when executed from the sc_report_wrapper.R
    print(args)
    return (args)
}

## ----
args <- get_args()
prod$parallel(args)

## ----
seurat_data <- NULL                                              # to keep all merged seurat objects
args$rds <- sort(args$rds)                                       # we want to have them sorted to make orig.ident values reproducible and not dependent on rds order
for (i in 1:length(args$rds)){
    current_rds <- args$rds[i]
    print(paste("Loading Seurat data from the", current_rds))
    current_seurat_data <- readRDS(current_rds)
    if (!("RNA" %in% names(current_seurat_data@assays))){
        print(
            paste(
                "Loaded Seurat object doesn't",
                "include RNA assay. Exiting."
            )
        )
        quit(save="no", status=1, runLast=FALSE)
    }
    if (!("Sample_Tag" %in% colnames(current_seurat_data@meta.data))){
        print(
            paste(
                "Loaded Seurat object doesn't",
                "include Sample_Tag metadata column.",
                "Exiting."
            )
        )
        quit(save="no", status=1, runLast=FALSE)
    }
    print(
        paste(
            "Loaded cells:", length(SeuratObject::Cells(current_seurat_data))
        )
    )
    current_seurat_data <- base::subset(                                                       # we don't need unassigned cells
        current_seurat_data,
        subset=(Sample_Tag != "Multiplet") & (Sample_Tag != "Undetermined")
    )
    print(
        paste(
            "After removing multiplets and undetermined:",
            length(SeuratObject::Cells(current_seurat_data))
        )
    )
    current_seurat_data@meta.data$Sample_Name <- NULL                                          # no reason to have two identical columns - Sample_Tag and Sample_Name
    current_seurat_data@meta.data$custom_sample <- current_seurat_data@meta.data$orig.ident    # to save the name created by the Rhapsody pipeline (might be not unique)
    current_seurat_data@meta.data$orig.ident <- i                                              # we need to know from which rds file the cells were loaded from
    current_seurat_data <- SeuratObject::RenameCells(                                          # need to rename the cells in case we have duplicated barcodes
        current_seurat_data,
        new.names=base::paste0(                                                                # s - sample, b - start of the original barcode
            "s", i, "b", SeuratObject::Cells(current_seurat_data)                              # we need "b" because cell barcodes are numerical, so we need a separator
        )                                                                                      # to avoid possible duplicated barcodes when adding "i" as a prefix
    )
    debug$print_info(current_seurat_data, args)

    if (is.null(seurat_data)){
        seurat_data <- current_seurat_data
    } else {
        seurat_data <- base::merge(
            seurat_data, y=current_seurat_data
        )
    }
}
debug$print_info(seurat_data, args)

## ----
print("Assigning datasets names based on the sample tags")
seurat_data <- io$extend_metadata(
    seurat_data=seurat_data,
    location=args$metadata,                                      # has only two columns: sample_tag and the arbitrary column with the names for those sample tags
    seurat_ref_column="Sample_Tag",                              # we already checked the presence of this column
    meta_ref_column="sample_tag",                                # we prefer lowercase formatiing in the metadata file
    seurat_target_columns="new.ident",                           # we will put the values from the second metadata column to the new.ident column
    split_by = if (args$split) "orig.ident" else NULL            # if true will add the values from the orig.ident column at the end of each new.ident
)
seurat_data@meta.data$Sample_Tag <- NULL                         # we don't need this column anymore
debug$print_info(seurat_data, args)

## ----
print("Updating cell barcodes to reflect sample tag names assignment")
seurat_data@meta.data <- seurat_data@meta.data %>%
                         dplyr::mutate(
                             orig.ident=base::match(                         # for each new.ident returns its position in the sorted unique new.ident vector
                                 new.ident,
                                 base::sort(
                                    base::unique(
                                        as.vector(as.character(new.ident))
                                    )
                                )
                             )
                         )
seurat_data <- SeuratObject::RenameCells(
    seurat_data,
    new.names=base::paste0(
        SeuratObject::Cells(seurat_data),
        "-",
        seurat_data@meta.data$orig.ident
    )
)
debug$print_info(seurat_data, args)

## ----
print("Extracting datasets identities from the Seurat object")
cell_identity_data <- seurat_data@meta.data %>%
                      dplyr::arrange(orig.ident) %>%                   # the order of the rows should be exacly the same as the suffixes added to the cell barcodes
                      dplyr::rename("library_id"="new.ident")  %>%     # to make it compatible with sc_rna_filter.R --identity input
                      dplyr::distinct(library_id)
io$export_data(
    cell_identity_data,
    paste0(args$output, "_aggr.tsv")
)

# ----
print("Exporting raw read counts to Cell Ranger format")
DropletUtils:::write10xCounts(
    path="filtered_feature_bc_matrix",
    x=SeuratObject::GetAssayData(seurat_data, assay="RNA", slot="counts"),
    type="sparse",
    version="3",
    overwrite=TRUE
)
utils::tar(
    paste0(args$output, "_bc_matrix.tar.gz"),
    "filtered_feature_bc_matrix",
    compression="gzip"
)
base::unlink("filtered_feature_bc_matrix", recursive=TRUE)

## ----
DefaultAssay(seurat_data) <- "RNA"
seurat_data <- NormalizeData(seurat_data, verbose=FALSE)                 # we normalize it to replace the possible content of the data slot
seurat_data <- Seurat::DietSeurat(                                       # should export only RNA assay with all features
    seurat_data,
    assays="RNA",
    counts=TRUE,
    data=TRUE,                                                           # setting FALSE here is not supported
    scale.data=FALSE
)
seurat_data@meta.data$condition <- seurat_data@meta.data$new.ident       # setting the default condition values
io$export_rds(seurat_data, paste(args$output, "_data.rds", sep=""))      # we save it in case we want to use in the sc_rna_azimuth.R
debug$print_info(seurat_data, args)

## ----
if(args$h5ad){
    io$export_h5ad(
        data=seurat_data,
        location=paste(args$output, "_counts.h5ad", sep=""),
        assay="RNA",
        slot="counts"
    )
}